### ISSUE TITLE
Nested rules not correctly typed with PostCSS plugin

### ISSUE THREAD

**Issue by daanvosdewael** [mrmckeb/typescript-plugin-css-modules#197]
**Describe the bug**
When using the [`postcss-nested`](https://github.com/postcss/postcss-nested) plugin to nest rules, the types are not generated as expected.

**To Reproduce**

1. Add a PostCSS config:
```js
// postcss.config.js
module.exports = {
  plugins: {
    'postcss-nested': {},
  },
};
```

2. Configure the plugin to have the `useConfig` boolean on the `postCssOptions` object set to `true`:
```json5
// tsconfig.json
{
  "name": "typescript-plugin-css-modules",
  "options": {
    "postCssOptions": {
      "useConfig": true
    }
  }
}
```

3. Make a CSS module file with nested rules:
```css
/* Foo.module.css */
.foo {
  width: 100%;

  &__bar {
    z-index: 1;
  }
}
```

4. Use the styles in JS:
```js
import styles from './Foo.module.css';
console.log(styles['foo__bar']); // Property 'foo__bar' does not exist on type '{ foo: string; }'.
```

**Expected behavior**
Because of the `&` in the selector, this nested rule becomes a new selector in addition to the root one.

The type definition of `styles` should be:
```ts
{
  foo: string;
  'foo__bar': string;
}
```

**Comment by andrey-skl** [comment]
Likely same as #163

**Comment by mrmckeb** [comment]
This is now resolved in `v4.2.1`:
- https://github.com/mrmckeb/typescript-plugin-css-modules/releases/tag/v4.2.1
- https://github.com/mrmckeb/typescript-plugin-css-modules/releases/tag/v4.2.0

**Comment by daanvosdewael** [comment]
Thanks for the fix! Unfortunately the new version does not fix my issue. I still only get the root selector as type definition. Could you please take a look again?

I have created an example repo here: https://github.com/daanvosdewael/typescript-plugin-css-modules-postcss-example

**Comment by mishantrop** [comment]
Same issue

- typescript-plugin-css-modules 4.2.3
- postcss 8.4.24
- postcss-nested 6.0.1

**Comment by daanvosdewael** [comment]
@mrmckeb I'm sorry to reply so late again about this issue, but my problem still exists with the latest version of this plugin. This related issue https://github.com/mrmckeb/typescript-plugin-css-modules/issues/163 with different PostCSS plugins also does not work.

Any change that you could look at this again? Or do I need to open another issue?

**Comment by ottetz** [comment]
same here
